### PR TITLE
Add snap offset option

### PR DESCRIPTION
**Pull request by kim366**

### CODE REVIEW

**Comment by pcate-coreonyx** [comment]
@kim366 your addition worked for me. The API section of the readme should be updated as well though to document the new prop, as well as updating the Usage section with a code sample.

**Comment by kim366** [comment]
Done :smile:

**Review by patrickcate — APPROVED** [review]
Tested and works for me.

**Comment by kim366** [comment]
Soo, we gonna pull?

**Comment by ux-engineer** [comment]
Has the maintainer gone in maintenance...?

**Review by rohitoneadvanced — APPROVED** [review]
PR looks good

**Review by rohitoneadvanced — APPROVED** [review]

**Pull request merged**
